language: generic
sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t selcukkubur/demoapp -f Dockerfile .
  - docker push selcukkubur/demoapp
